name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  Install-Python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check python version
        if: contains(python --version, "3.10")
        run: python --version
