name: PHP-CI

on:
  push:
    branches: [main] # Trigger the workflow on main branch push
  pull_request:
    branches: [main] # Trigger the workflow on main branch pull requests

jobs:
  PHP-Composer:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP 8.1 if not installed
      run: |
        if php -v | grep -q "PHP 8.1"; then
          echo "PHP 8.1 is installed"
          echo "skipping PHP install"
        else
          echo "PHP 8.1 is not installed"
          echo "Installing PHP 8.1"
          sudo apt-get update
          sudo apt-get install -y php-cli php-zip unzip
        fi


    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        
    - name: Install Laravel v10.0.0
      run: |
        composer create-project --prefer-dist laravel/laravel:v10.0.0 laravel

    - name: Run composer
      run: |
        cd laravel
        composer install
